import { defineObject, FieldType } from 'twenty-sdk/define';

export const INCOMING_PAYMENT_UNIVERSAL_IDENTIFIER =
  'f61281c6-9b36-4326-b8dc-d421df3015ec';
export const INCOMING_PAYMENT_NAME_FIELD_UNIVERSAL_IDENTIFIER =
  '2a83295c-767f-434f-bb63-2ad53356d0ed';

export default defineObject({
  universalIdentifier: INCOMING_PAYMENT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'incomingPayment',
  namePlural: 'incomingPayments',
  labelSingular: 'Incoming payment',
  labelPlural: 'Incoming payments',
  description: 'Fiat or other value actually received by Finite',
  icon: 'IconCashBanknote',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier:
    INCOMING_PAYMENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: INCOMING_PAYMENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: 'bb2bcdb8-baf2-43e9-885e-419c08ff9a35',
      type: FieldType.NUMBER,
      name: 'nativeAmount',
      label: 'Native amount',
      description: 'Amount in the asset actually received, such as USD or BTC',
      icon: 'IconNumbers',
    },
    {
      universalIdentifier: '3509fb1a-d245-479a-98ed-a321d4ad0928',
      type: FieldType.TEXT,
      name: 'assetCode',
      label: 'Asset code',
      description: 'Currency or asset code, such as USD or BTC',
      icon: 'IconCoins',
    },
    {
      universalIdentifier: '2bdec799-39e3-4e3c-ae6c-65b074eadef3',
      type: FieldType.CURRENCY,
      name: 'reportingValueUsd',
      label: 'Receipt-time value (USD)',
      description: 'USD reporting value at receipt time when known',
      icon: 'IconCurrencyDollar',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: '56518c8d-b198-4081-a096-eaf3a0b60dbc',
      type: FieldType.DATE_TIME,
      name: 'receivedAt',
      label: 'Received at',
      icon: 'IconCalendarTime',
    },
    {
      universalIdentifier: '6677378d-bc27-4c4a-80da-842df4680fbb',
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconActivity',
      defaultValue: "'RECEIVED'",
      options: [
        {
          id: '3ab9446c-0639-49a1-800a-e2426549201b',
          value: 'RECEIVED',
          label: 'Received',
          position: 0,
          color: 'green',
        },
        {
          id: '6b48e6e8-cc9d-4213-8c8a-0d002fc346ee',
          value: 'REFUNDED',
          label: 'Refunded',
          position: 1,
          color: 'orange',
        },
        {
          id: '6e95d1a5-0f7e-4ba9-abcd-64a0e603531d',
          value: 'VOIDED',
          label: 'Voided',
          position: 2,
          color: 'gray',
        },
      ],
    },
    {
      universalIdentifier: '2aaedc22-6bb8-42f0-a03f-38f4fbffff09',
      type: FieldType.SELECT,
      name: 'method',
      label: 'Payment method',
      icon: 'IconCreditCardPay',
      defaultValue: "'OTHER'",
      options: [
        {
          id: '705a442a-5318-4695-97a3-924fd654cf4c',
          value: 'BANK',
          label: 'Bank',
          position: 0,
          color: 'blue',
        },
        {
          id: 'a9ba8523-b0ae-464b-92f5-37e2959a4028',
          value: 'CARD',
          label: 'Card',
          position: 1,
          color: 'purple',
        },
        {
          id: '5b88619c-1a28-48b3-82c4-fdae4e44dfc1',
          value: 'DIGITAL_ASSET',
          label: 'Digital asset',
          position: 2,
          color: 'orange',
        },
        {
          id: 'a09e4f35-5d61-41bc-b33b-9d2f75a72cef',
          value: 'CASH',
          label: 'Cash',
          position: 3,
          color: 'green',
        },
        {
          id: '9d045425-5750-4a83-9aef-a7c14d4fedfd',
          value: 'OTHER',
          label: 'Other',
          position: 4,
          color: 'gray',
        },
      ],
    },
    {
      universalIdentifier: 'bb7d5344-3bc7-4ab9-9675-dc686f1c22fc',
      type: FieldType.TEXT,
      name: 'network',
      label: 'Network',
      description: 'Payment rail or digital-asset network when relevant',
      icon: 'IconNetwork',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: '664a76c5-4e52-4bfb-ae30-427fc41168f2',
      type: FieldType.TEXT,
      name: 'transactionReference',
      label: 'Transaction reference',
      description: 'Bank, processor, or blockchain transaction reference',
      icon: 'IconHash',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: 'ebe95bdd-71f1-465d-b290-8b0152ffaffe',
      type: FieldType.TEXT,
      name: 'sourceReference',
      label: 'Source reference',
      icon: 'IconLink',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: '6b2737d7-61bf-4b0e-a416-0fe4e9dbdfd2',
      type: FieldType.BOOLEAN,
      name: 'reconciliationWarning',
      label: 'Reconciliation warning',
      icon: 'IconAlertCircle',
      defaultValue: false,
    },
  ],
});
